### ISSUE TITLE
NoClassDefFoundError: org/bouncycastle/jcajce/util/JcaJceHelper

### ISSUE THREAD

**Issue by zerikv** [xebialabs/overthere#154]
Hi,

With Overthere 2.4.8 I get the following error when I try a SSH connection with a RSA key
```
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/util/JcaJceHelper
       at net.schmizz.sshj.userauth.keyprovider.PKCS8KeyFile.readKeyPair(PKCS8KeyFile.java:134) ~[sshj-0.11.0.jar:na]
       at net.schmizz.sshj.userauth.keyprovider.PKCS8KeyFile.getPublic(PKCS8KeyFile.java:78) ~[sshj-0.11.0.jar:na]
       at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:44) ~[sshj-0.11.0.jar:na]
       at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62) ~[sshj-0.11.0.jar:na]
       at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:81) ~[sshj-0.11.0.jar:na]
       at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:63) ~[sshj-0.11.0.jar:na]
       at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:68) ~[sshj-0.11.0.jar:na]
       at net.schmizz.sshj.SSHClient.auth(SSHClient.java:211) ~[sshj-0.11.0.jar:na]
       at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:316) ~[sshj-0.11.0.jar:na]
       at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:335) ~[sshj-0.11.0.jar:na]
       at com.xebialabs.overthere.ssh.SshConnection.connect(SshConnection.java:183) ~[overthere-2.4.8-carl-3.jar:na]
       at com.xebialabs.overthere.ssh.SshSftpConnection.connect(SshSftpConnection.java:53) ~[overthere-2.4.8-carl-3.jar:na]
       at com.xebialabs.overthere.ssh.SshConnectionBuilder.connect(SshConnectionBuilder.java:530) ~[overthere-2.4.8-carl-3.jar:na]
       at com.xebialabs.overthere.Overthere.buildConnection(Overthere.java:132) ~[overthere-2.4.8-carl-3.jar:na]
       at com.xebialabs.overthere.Overthere.getConnection(Overthere.java:113) ~[overthere-2.4.8-carl-3.jar:na]
```

I have added the `bcmail` dependency in the build.gradle, and also upgraded to version 1.51 because it's the version used by sshj 0.11.0:
```
-  runtime 'org.bouncycastle:bcprov-jdk15on:1.49'
+  runtime 'org.bouncycastle:bcprov-jdk15on:1.51'
+  runtime 'org.bouncycastle:bcmail-jdk15on:1.51'
```

Regards,
Eric

**Comment by hierynomus** [comment]
@zerikv Does this still happen with the latest 4.2.0 release?

**Comment by vpartington** [comment]
Closed due to lack of activity.
