### ISSUE TITLE
STATUS_INTERNAL_ERROR (0xc00000e5): QueryInfo failed for SMB2FileId

### ISSUE THREAD

**Issue by nddipiazza** [xebialabs/overthere#235]
We are crawling an extremely massive windows DFS.

When opening a directory, one out of the 10 DFS throws this error:

```
Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_INTERNAL_ERROR (0xc00000e5): QueryInfo failed for SMB2FileId{persistentHandle=c2 b3 19 32 e4 e2 56 7d}
    at com.hierynomus.smbj.share.Share.receive(Share.java:366) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.Share.sendReceive(Share.java:346) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.Share.queryInfo(Share.java:188) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.DiskShare.getFileInformation(DiskShare.java:272) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.DiskEntry.getFileInformation(DiskEntry.java:65) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.DiskEntry.getFileInformation(DiskEntry.java:61) ~[smbj-0.8.5.jar:0.8.5]
```

How can I figure out what the problem here is? 

Code:

```
try (Directory _folder = share.openDirectory(folderPath, of(GENERIC_READ), null, of(FILE_SHARE_READ), FILE_OPEN, null)) {
   _folder.getFileInformation();
}
```

**Comment by nddipiazza** [comment]
github.com mesed with me - created in wrong proj
